/**
 * gRPC client layer: shared client instances and per-service RPC wrappers.
 * Import from here for backward compatibility, or from ./user, ./file, ./system for direct access.
 */

export { userClient, resourceClient, fileClient, systemClient } from "./client";
export {
  userGet,
  userGetUser,
  userUpdateUser,
  userDeleteUser,
  userSearchUsersByName,
  userGetUserByEmail,
  userListEnrollments,
  userEnrollUser,
  userUnenrollUser,
  userListCourses,
  userCreateCourse,
  userDeleteCourse,
  userListAllUsers,
} from "./user";
export {
  resourceCreateResource,
  resourceGetResource,
  resourceListResources,
  resourceListAllResources,
  resourceUpdateResource,
  resourceDeleteResource,
  resourceRecordAccessLog,
} from "./resource";
export { fileGet, fileGetUploadUrl, fileGetDownloadUrl } from "./file";
export {
  systemGet,
  systemGetMetricsOverview,
  systemGetMetricsTimeseries,
  systemListIncidents,
  systemRecordMetricEvent,
} from "./system";
export type {
  GetResponse,
  GetUploadUrlRequest,
  GetUploadUrlResponse,
  GetDownloadUrlRequest,
  GetDownloadUrlResponse,
  ResourceResponse,
  CreateResourceRequest,
  GetResourceRequest,
  ListResourcesRequest,
  ListResourcesResponse,
  UpdateResourceRequest,
  DeleteResourceRequest,
  DeleteResourceResponse,
  RecordAccessLogRequest,
  RecordAccessLogResponse,
  GetUserResponse,
  UpdateUserRequest,
  DeleteUserResponse,
  SearchUsersByNameResponse,
  GetUserByEmailResponse,
  CourseEnrollment,
  ListEnrollmentsResponse,
  EnrollUserRequest,
  EnrollUserResponse,
  UnenrollUserRequest,
  UnenrollUserResponse,
  CourseInfo,
  ListCoursesResponse,
  CreateCourseRequest,
  DeleteCourseRequest,
  DeleteCourseResponse,
  UserInfo,
  ListAllUsersResponse,
  ListAllResourcesResponse,
  GetMetricsOverviewRequest,
  GetMetricsOverviewResponse,
  GetMetricsTimeseriesRequest,
  GetMetricsTimeseriesResponse,
  Incident,
  ListIncidentsRequest,
  ListIncidentsResponse,
  MetricsPoint,
  RecordMetricEventRequest,
  RecordMetricEventResponse,
  ServiceMetricSummary,
} from "../../types/grpc";
