apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: lrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.digitalocean.com/ece1779-lrms/auth:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PORT
              value: "4000"
            - name: FRONTEND_URL
              value: "http://lrms.localtest.me"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: BETTER_AUTH_SECRET
            - name: BETTER_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: BETTER_AUTH_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: PROTO_PATH
              value: /app/proto/services.proto
            - name: USER_SERVER
              value: user-server:5001
            - name: FILE_SERVER
              value: file-server:5002
            - name: SYSTEM_SERVER
              value: system-server:5003
