apiVersion: v1
kind: Secret
metadata:
  name: lrms-secrets
  namespace: lrms
type: Opaque

stringData:
  DATABASE_URL: "REPLACE_WITH_DATABASE_URL"
  FILE_SERVER_DATABASE_URL: "REPLACE_WITH_FILE_SERVER_DATABASE_URL"
  BETTER_AUTH_SECRET: "REPLACE_WITH_BETTER_AUTH_SECRET"
  BETTER_AUTH_URL: "REPLACE_WITH_BETTER_AUTH_URL"
  GOOGLE_CLIENT_ID: "REPLACE_WITH_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "REPLACE_WITH_GOOGLE_CLIENT_SECRET"
  SPACES_REGION: "tor1"
  SPACES_ENDPOINT: "https://tor1.digitaloceanspaces.com"
  SPACES_BUCKET: "REPLACE_WITH_SPACES_BUCKET"
  SPACES_KEY: "REPLACE_WITH_SPACES_KEY"
  SPACES_SECRET: "REPLACE_WITH_SPACES_SECRET"
