apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-server
  namespace: lrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-server
  template:
    metadata:
      labels:
        app: system-server
    spec:
      containers:
        - name: system-server
          image: REPLACE_WITH_SYSTEM_SERVER_IMAGE
          ports:
            - containerPort: 5003