apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: lrms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          image: registry.digitalocean.com/ece1779lrms/user-server:latest
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lrms-secrets
                  key: DATABASE_URL
